version: '3'

services:
  # Laravel Application Service
  # Serviço da Aplicação Laravel
  app:
    build: .
    volumes:
      - .:/var/www
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=laravel
      - DB_USERNAME=postgres
      - DB_PASSWORD=secret
    depends_on:
      - db

  # PostgreSQL Database Service
  # Serviço do Banco de Dados PostgreSQL
  db:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=laravel
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Nginx Web Server
  # Servidor Web Nginx
  webserver:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

# Persistent Data Volume
# Volume persistente para dados
volumes:
  postgres_data: